### ISSUE TITLE
通过 tsconfig 把 angular 别名设置到 angular 文件夹后，启动报错。

### ISSUE THREAD

**Issue by danranVm** [DimaLiLongJi/read-angular#1]
- Cannot find name 'goog'.
- Cannot find name 'Zone'
- Cannot find name 'Task'

根据错误提示，我在 tsconfig.json 里新增如下配置，还是报错，请问是为什么？
```
  "files": [
    "./goog.d.ts",
    "./system.d.ts",
    "./node_modules/zone.js/dist/zone.js.d.ts"
  ],
```

**Comment by DimaLiLongJi** [comment]
你先cd到angular npm i下然后再切到my-demo再npm i下看下还有吗 我本地没有这个报错暂时

**Comment by DimaLiLongJi** [comment]
不好意思 点错了给关闭了

**Comment by danranVm** [comment]
嗯 按你的说法已经解决了。 多谢。
